class Settings:
    TIME_STEP_SIZE = 1/5
    SIMULATION_FPS = 30
    SIMULATION_FRAME_SIZE = (400, 400)
    RENDERING_VIEWPORT_SIZE = (512, 512)
    RENDERING_SPACECRAFT_DEBUGGING = True
    RENDER_SPACECRAFT_INFORMATION = True
